spring:
  application:
    name: Where
  jwt:
    secret: ${JWT_SECRET}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://where-db1.c3sewig4iszd.ap-northeast-2.rds.amazonaws.com:3306/where_db
    username: admin
    password: ${RDS_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create

  jackson:
    time-zone: Asia/Seoul

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            authorization-grant-type: authorization_code

          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response.id

          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize
            token-uri: https://appleid.apple.com/auth/token
            user-info-uri: https://appleid.apple.com
            user-name-attribute: sub

cloud:
  aws:
    s3:
      bucket: "where-bucket32"

    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}

server:
  port: 443
  ssl:
    enabled: true
    key-store: /home/ubuntu/keystore.p12
    key-store-password: ${SSL_PASSWORD}
    key-store-type: PKCS12
  forward-headers-strategy: native

logging:
  level:
    org.springframework: debug

dotenv:
  enabled: true
