-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg2XW0iHyjgdHkQ4DQ
3wK6Rg9ptU2lgJ3+ZSrGyJpwhNagCgYIKoZIzj0DAQehRANCAARhDEgTQNfILAHN
9MfYGAOmfF8krPv8yjkXxDglSk6lcbmbQE1hy+Y0fEIaP9hC2XG5q8PFcZgMkB9l
h/HV2apb
-----END PRIVATE KEY-----